FORMAT: 1A
HOST: https://api.spark.io/v1/devices/53ff6b066667574854472367/

# Kaia Hardware

Kaia Hardware api is a collection of REST api's to access Kaia hardware functions.

# Kaia Functions - API Root [/{?access_token}]

This resource provides a list of all functions and variables available to Kaia and
does not have any attributes. Instead it offers the initial API affordances in the 
form of the links in the JSON body.

## List Kaia Functions  [GET]

+ id - ID of the hardware being retrieved
+ name - Name cooresponding to the ID being retrieved
+ connected - Returns status of connection to Particle cloud
+ variables - returns all variables the user can GET
+ functions - returns all functions the user can POST to

+ Parameters
    + access_token: 9b547a8ed26de0a21babe4eaa82d04287694a7b2 (required, string) - The token for the Kaia system

+ Response 200 (application/json)

        {
            "id": "53ff6b066667574854472367",
            "name": "GLaDOS",
            "connected": true,
            "variables": {
                "brightness": "int32",
                "hardwareRev": "string",
                "softwareVer": "string"
            },
            "functions": [
                "light",
                "brightness",
                "theme",
                "autoBright"
            ],
            "cc3000_patch_version": "1.29",
            "product_id": 0,
            "last_heard": "2015-12-25T00:47:53.812Z"
        }

## Kaia Hardware [/hardwareRev{?access_token}]
Display the hardware revision of Kaia with this API

+ Parameters
    + access_token: 9b547a8ed26de0a21babe4eaa82d04287694a7b2 (required, string) - The token for the Kaia system

### Display Kaia hardware revision [GET]
Returns Kaia's hardware revision as a String. (Need to come up with versioning scheme)

+ name - name of the variable in the request
+ result - string displaying the hardware revision of Kaia (need to come up with versioning scheme)
+ connected - device connection state to the Particle cloud
+ deviceID - ID of the selected device

+ Response 200 (application/json)

        {
          "cmd": "VarReturn",
          "name": "hardwareRev",
          "result": "1.0",
          "coreInfo": {
            "last_app": "",
            "last_heard": "2015-12-24T21:18:53.969Z",
            "connected": true,
            "last_handshake_at": "2015-12-24T21:10:49.268Z",
            "deviceID": "53ff6b066667574854472367",
            "product_id": 0
          }
        }

## Kaia Software [/softwareVer{?access_token}]
Display the software version of Kaia with this API

+ Parameters
    + access_token: 9b547a8ed26de0a21babe4eaa82d04287694a7b2 (required, string) - The token for the Kaia system

### Display Kaia software version [GET]
Returns Kaia's software version as a String. (Need to come up with versioning scheme)

+ name - name of the variable in the request
+ result - string displaying the software version of Kaia (need to come up with versioning scheme)
+ connected - device connection state to the Particle cloud
+ deviceID - ID of the selected device

+ Response 200 (application/json)

        {
          "cmd": "VarReturn",
          "name": "softwareVer",
          "result": "1.1",
          "coreInfo": {
            "last_app": "",
            "last_heard": "2015-12-24T21:18:53.969Z",
            "connected": true,
            "last_handshake_at": "2015-12-24T21:10:49.268Z",
            "deviceID": "53ff6b066667574854472367",
            "product_id": 0
          }
        }
        
## Kaia Light [/light{?access_token}]
You may change (or request?) the state of Kaias LED light with this endpoint. 
This action takes a JSON payload as part of the request.

+ Parameters
    + access_token: 9b547a8ed26de0a21babe4eaa82d04287694a7b2 (required, string) - The token for the Kaia system

### Toggle Kaia Light [POST]
This action takes a JSON payload as part of the request. 
The user can specify "on" or "off" to toggle the LED light.

+ args - you must specify the state of the LED as "on" or "off" 

+ Request (application/json)

        {
            "args":"on"
        } 
        
+ Response 200 (application/json)

        {
            "id": "53ff6b066667574854472367",
            "last_app": "",
            "connected": true,
            "return_value": 1
        }
        
## Kaia Brightness [/brightness{?access_token}]
You may change or request the brightness of Kaias LED light with this endpoint. 

+ Parameters
    + access_token: 9b547a8ed26de0a21babe4eaa82d04287694a7b2 (required, string) - The token for the Kaia system

### Display Kaia brightness [GET]
Returns the brightness level of Kaia's LED between 0 (off) and 255 (on)

+ name - Name of the variable in the request
+ result - integer value between 0 (off) - 255 (on) of the brightness level
+ connected - device connection state to the Particle cloud
+ deviceID - ID of the selected device

+ Response 200 (application/json)

        {
          "cmd": "VarReturn",
          "name": "brightness",
          "result": 188,
          "coreInfo": {
            "last_app": "",
            "last_heard": "2015-12-24T19:44:22.803Z",
            "connected": true,
            "last_handshake_at": "2015-12-24T19:00:48.778Z",
            "deviceID": "53ff6b066667574854472367",
            "product_id": 0
          }
        }


### Modify Kaia Brightness [POST]
This action takes a JSON payload as part of the request. 
The user can specify between integer 0 (off) to 255 (on) to adjust the brightness of Kaia's LED

+ args - you must specify the brightness of the LED as an integer between 0 and 255
+ return_value - returns the integer value Kaia was able to change the LED to 
(ex. if the user specifies 120 and the microcontroller can successfully change the brightness 
to 120, the return_value will indicate "120"

+ Request (application/json)

        {
            "args":"180"
        } 
        
+ Response 200 (application/json)

        {
            "id": "53ff6b066667574854472367",
            "last_app": "",
            "connected": true,
            "return_value": 180
        }
            
## Kaia Auto-Brightness [/autoBright{?access_token}]
You may interact with Kaia's auto-brightness feature with this endpoint. 

+ Parameters
    + access_token: 9b547a8ed26de0a21babe4eaa82d04287694a7b2 (required, string) - The token for the Kaia system

### Toggle Kaia Auto-Brightness [POST]
This action takes a JSON payload as part of the request. 
The user can enable or disable auto-brightness of the Kaia system by posting an "on" or "off" argument

+ args - you must specify to enable or disable the autobrightness feature with "on" or "off"
+ return_value - returns the state of the auto-brightness variable, 1 (on) or 0 (off) and a -1 if an error occured.

+ Request (application/json)

        {
            "args":"on"
        } 
        
+ Response 200 (application/json)

        {
          "id": "53ff6b066667574854472367",
          "last_app": "",
          "connected": true,
          "return_value": 1
        }
